name: paddle
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - ccache=4.11.3=h80c52d3_0
  - icu=78.1=h33c6efd_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran-ng=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=he0feb66_16
  - libhiredis=1.0.2=h2cc385e_0
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libsqlite=3.51.1=hf4e2dac_1
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libuuid=2.41.3=h5347b49_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openblas=0.3.30=pthreads_h6ec200e_4
  - openssl=3.6.0=h26f9b46_0
  - pip=25.3=pyh8b19718_0
  - python=3.10.19=h3c07f61_2_cpython
  - readline=8.3=h853b02a_0
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_ha0e22de_103
  - wheel=0.45.1=pyhd8ed1ab_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - aistudio==0.0.1
      - aistudio-sdk==0.2.6
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - asttokens==3.0.1
      - async-timeout==5.0.1
      - attrs==25.4.0
      - audioread==3.1.0
      - av==16.0.1
      - babel==2.17.0
      - bce-python-sdk==0.9.59
      - blinker==1.9.0
      - bokeh==3.8.2
      - boltons==25.0.0
      - bottleneck==1.6.0
      - braceexpand==0.1.7
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - colorlog==6.10.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==4.4.2
      - decorator==5.2.1
      - dill==0.3.4
      - distance==0.1.3
      - editdistance==0.8.1
      - einops==0.8.1
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastapi==0.128.0
      - ffmpeg-python==0.2.0
      - ffmpy==1.0.0
      - filelock==3.20.2
      - flask==3.1.2
      - flask-babel==4.0.0
      - flatbuffers==25.12.19
      - flatten-dict==0.4.2
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - ftfy==6.3.1
      - future==1.0.0
      - g2p-en==2.1.0
      - g2pm==0.1.2.5
      - h11==0.16.0
      - h5py==3.15.1
      - hf-transfer==0.1.9
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.2.3
      - humanfriendly==10.0
      - hyperpyyaml==1.2.3
      - idna==3.11
      - importlib-resources==6.5.2
      - inflect==7.5.0
      - intervaltree==3.2.1
      - ipython==8.38.0
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jieba==0.42.1
      - jinja2==3.1.6
      - joblib==1.5.3
      - jsonlines==4.0.0
      - kaldiio==2.18.1
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - librosa==0.11.0
      - ligo-segments==1.4.0
      - llvmlite==0.46.0
      - loguru==0.7.3
      - lxml==6.0.2
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - mido==1.3.3
      - ml-dtypes==0.5.4
      - mock==5.2.0
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - multiprocess==0.70.12.2
      - nara-wpe==0.0.11
      - narwhals==2.14.0
      - networkx==3.4.2
      - nltk==3.9.2
      - note-seq==0.0.5
      - numba==0.63.1
      - numpy==1.26.4
      - nvidia-cublas==13.0.2.14
      - nvidia-cuda-cccl==13.0.85
      - nvidia-cuda-cupti==13.0.85
      - nvidia-cuda-nvrtc==13.0.88
      - nvidia-cuda-runtime==13.0.88
      - nvidia-cudnn-cu13==9.13.0.50
      - nvidia-cufft==12.0.0.61
      - nvidia-cufile==1.15.1.6
      - nvidia-curand==10.4.0.35
      - nvidia-cusolver==12.0.4.66
      - nvidia-cusparse==12.6.3.3
      - nvidia-cusparselt-cu13==0.8.1
      - nvidia-nccl-cu13==2.28.3
      - nvidia-nvjitlink==13.0.88
      - nvidia-nvtx==13.0.85
      - omegaconf==2.3.0
      - onnx==1.17.0
      - onnxoptimizer==0.3.13
      - onnxruntime==1.23.2
      - opencc==1.1.9
      - opencc-python-reimplemented==0.1.7
      - opencv-python==4.6.0.66
      - opt-einsum==3.3.0
      - packaging==25.0
      - paddle2onnx==2.0.1
      - paddlefsl==1.1.0
      - paddlenlp==2.8.1
      - paddlepaddle-gpu==3.2.2
      - paddlesde==0.2.5
      - paddleslim==2.6.0
      - paddlespeech==0.0.0
      - paddlespeech-feat==0.1.0
      - pandas==2.3.3
      - parameterized==0.9.0
      - parso==0.8.5
      - pathos==0.2.8
      - pattern-singleton==1.2.0
      - pexpect==4.9.0
      - pillow==12.0.0
      - platformdirs==4.5.1
      - polygraphy==0.49.26
      - pooch==1.8.2
      - portalocker==3.2.0
      - pox==0.3.6
      - ppdiffusers==0.29.0
      - ppft==1.7.7
      - praatio==6.2.0
      - pretty-midi==0.2.11
      - prettytable==3.17.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==3.20.2
      - psutil==7.2.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==22.0.0
      - pybind11==3.0.1
      - pycparser==2.23
      - pycryptodome==3.23.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydub==0.25.1
      - pygments==2.19.2
      - pyloudnorm==0.2.0
      - pyparsing==3.3.1
      - pypinyin==0.55.0
      - pypinyin-dict==0.9.0
      - pytest-runner==6.0.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyworld==0.3.5
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - rarfile==4.2
      - regex==2025.11.3
      - requests==2.32.5
      - requests-mock==1.12.1
      - resampy==0.4.3
      - rich==14.2.0
      - ruamel-yaml==0.18.17
      - ruamel-yaml-clib==0.2.15
      - sacrebleu==2.5.1
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sentencepiece==0.2.1
      - seqeval==1.2.2
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soundfile==0.13.1
      - soxr==1.0.0
      - stack-data==0.6.3
      - starlette==0.50.0
      - swig==4.4.1
      - sympy==1.14.0
      - tabulate==0.9.0
      - textgrid==1.6.1
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - timer==0.3.0
      - tojyutping==3.2.0
      - tool-helpers==0.1.2
      - tornado==6.5.4
      - tqdm==4.67.1
      - traitlets==5.14.3
      - trampoline==0.1.2
      - typeguard==4.4.4
      - typer==0.21.0
      - typer-slim==0.21.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==1.26.20
      - uvicorn==0.40.0
      - visualdl==2.5.3
      - wcwidth==0.2.14
      - webrtcvad==2.0.10
      - websockets==15.0.1
      - werkzeug==3.1.4
      - xxhash==3.6.0
      - xyzservices==2025.11.0
      - yacs==0.1.8
      - yarl==1.22.0
      - zhon==2.1.1
prefix: ~/miniconda3/envs/paddle
